### ISSUE TITLE
Add how to contribute guide

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/Documentation#16]

**Comment by pranshi112** [comment]
Can I work on this issue?

**Comment by pnijhara** [comment]
FIrst, complete the one on which you are currently working.

**Comment by salonigupta1** [comment]
Can I work on this issue?

**Comment by syedjawadakhtar** [comment]
Are you people adding about PRs?
Then please do add that every PR must have an **assignee** with proper **labels** and a **milestone** too (if any).
