### ISSUE TITLE
Update `about.md` page

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/Documentation#17]

**Comment by TamkeenFatima** [comment]
May I work on this?

**Comment by pnijhara** [comment]
Go ahead!

**Comment by Zaidtech** [comment]
Can I Work on this issue?
@pnijhara  can you please provide a short description of this issue.

**Comment by pnijhara** [comment]
@Zaidtech we appreciate outside contributions. But as you can see it is already assigned.
Look for other issues.

**Comment by pnijhara** [comment]
@Zaidtech if you want you can work on #25

**Comment by Zaidtech** [comment]
@pnijhara  Thanks.

**Comment by pnijhara** [comment]
Reply there if you want to get assigned!
