### ISSUE TITLE
Update index.md

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/Documentation#18]
There are lots of errors in already existing documentation. Follow markdown best practices and update them.

> Suggestion: Use VScode and install markdown linter extension. It will suggest you changes.

**Comment by pranshi112** [comment]
Can I work on this issue?

**Comment by pnijhara** [comment]
Yes! go ahead!

**Comment by pnijhara** [comment]
@pranshi112 take help from this. We have to follow the rules mentioned here https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md

Also if you are using vscode then please intall markdown linter extension. It will give you suggestions based on this doc.
