### ISSUE TITLE
BMS file is in docx and can't be rendered on github. Change to pdf/markdown

### ISSUE THREAD

**Issue by mohdomama** [auvzhcet/Documentation#2]

**Comment by pnijhara** [comment]
@mohdomama Markdown is a very popular plain text markup format, but the Python community uses an alternative called reST. We can give .rst format a try. Could be a new begining.

**Comment by mohdomama** [comment]
Go for it, if other people are ready to learn something new. 
Also, look for Makrdown to rST convertor.

**Comment by RJ722** [comment]
Use pandoc. Also, use markdown for short projects -- small and lightweight.

Using rst is helpful for larger projects with intricate design documents, or in conjunction with LaTex.

**Comment by pnijhara** [comment]
@mohdomama @RJ722 Thank you for advice. I am using markdown for now. Will look rst for documentation of ROS.
