### ISSUE TITLE
Add how to start new repository Contributing guide

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/Documentation#25]
Add a how-to guide for starting a repository in AUV ZHCET organization.

**Comment by pnijhara** [comment]
@syedjawadakhtar Is this issue different from #16 ?

**Comment by syedjawadakhtar** [comment]
#16 is for contributing to this repository - The documentation repository. 
A subheading is to be added for starting/contributing to a new/existing repository in auvzhcet organization.

**Comment by Zaidtech** [comment]
Can I work on this issue?

**Comment by pnijhara** [comment]
@Zaidtech Please start writing!
@syedjawadakhtar will coordinate. Feel free to ask for any type of help here.

**Comment by Zaidtech** [comment]
Sure! I have started writing.
This is my first issue in the open-source world: cause me to take a lot of time

**Comment by Zaidtech** [comment]
one more thing, I tried doing 
`git remote add upstream <SSH> ` it didn't work  
 but with the **HTTP** link, it did. 
Can you please make it clear @pnijhara

**Comment by Zaidtech** [comment]
@syedjawadakhtar I am facing checklist issues, I made an initial pull request but failing checklist I deleted it.
How can I fix it?

**Comment by syedjawadakhtar** [comment]
@Zaidtech Can you elaborate what the checklist issue was? 
I'm not getting you.

**Comment by Zaidtech** [comment]
![CheckList_issue](https://user-images.githubusercontent.com/56652371/86886030-dfb5e280-c113-11ea-9dd9-78ed2a3a5363.png)

@syedjawadakhtar  Should I continue to make a PR even if my PR fails semantic check?

**Comment by pnijhara** [comment]
Ok, So Zaid hasn't written PR title correctly. It should have started with doc: or chore: whatever you feel to add according to your work.
@Zaidtech read from the resources that are mentioned in `CONTRIBUTING.md`. It will help you in writing good commit messages and PR titles.

**Comment by Zaidtech** [comment]
Oh! thanks, @pnijhara. 
It is fun learning to make my first PR.
Will be completing soon.

**Comment by Zaidtech** [comment]
@pnijhara I opened a PR, please review the same.

**Comment by pnijhara** [comment]
Looking!
Thank you!
