### ISSUE TITLE
Complete Management docs

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/Documentation#31]
Complete management responsibilities:
- Event/Workshop Manger
- Sponsorship Manager (Online and Offline)
- Creative Manager
- Videographer/Editor
- Alumni Relations Officer
- Treasurer

**Comment by syedjawadakhtar** [comment]
First phase of adding all the documents of Management team has been completed.

**Comment by pnijhara** [comment]
> First phase of adding all the documents of Management team has been completed.

Congratulations!
