### ISSUE TITLE
docs: Update README.md #28

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/Documentation#33]
There are certain changes required in the issue docs: Update README.md #28

1. Copy each teams roles from the README.md
2. Make a file for each role in the respective folders with `role.md`. 
eg. for fabrication engineer cut the complete content in README.md and paste it in a new file `fabrication.md` in `mechanical` folder
3. Provide the links to the teams (Mechanical, computer...) respective README.md in the main README.md only.

README.md must be short with proper directions.

**Comment by yash1412** [comment]
can i work on this issue?

**Comment by pnijhara** [comment]
@yash1412 let @syedjawadakhtar handle this. This issue sounds to be a complicating one to me.

**Comment by pnijhara** [comment]
@syedjawadakhtar could you please work on this issue?
I think you can manage stuff better.

**Comment by syedjawadakhtar** [comment]
@yash1412 has done some great work. Let him complete it!
