### ISSUE TITLE
Update navigation bar with proper links

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/Documentation#38]
**Is your feature request related to a problem? Please describe.**
Previous few PRs added new files to the dos, however, navigation links are not yet updated.

**Describe the solution you'd like**
A fix can be made by updating `mkdocs.yml` file.

**Additional context**
Table of content and navigation are to be updated with every PR. Must be a mendatory task if adding a new file to docs IMHO.

**Comment by pranshi112** [comment]
Can I work on this issue?
