### ISSUE TITLE
Update electronic's (README.md) table of content

### ISSUE THREAD

**Issue by pnijhara** [auvzhcet/Documentation#40]
## Team Documentation

The electronics team recently has added new files in their docs. The table of content needs to updated ASAP.

**Comment by TamkeenFatima** [comment]
Also, the BMS for lithium polymer battery pack link needs to be updated.
The file is inaccessible in the 'Electronics Doc'

**Comment by TamkeenFatima** [comment]
I think the previous name was more logical (compared to bms_Engineer.md), as it is a report.

**Comment by pnijhara** [comment]
@yash1412 please take this one also.

**Comment by yash1412** [comment]
ok
