### ISSUE TITLE
Update: CONTRIBUTING.md

### ISSUE THREAD

**Issue by syedjawadakhtar** [auvzhcet/Documentation#43]
A lot of typos and issues with issue #16. 
Who was working on that issue @pnijhara?
Please assign them back

**Comment by pnijhara** [comment]
@salonigupta1 could you please take a look into this?

**Comment by salonigupta1** [comment]
okay

**Comment by syedjawadakhtar** [comment]
@salonigupta1 
Changes:
1. Subheadings must not be all caps.
2. Provide links to documents wherever mentioning them. e.g. when mentioning about code of conduct in the first para
3. I think the "pull request guidelines" with good examples, can be added to the "git guide" provided in #49.
4. Check for spacing between each bullet point and content, so that proper indentation is followed.
5. To have a hassle-free typo check, use [**Grammarly**](https://app.grammarly.com/).

**Comment by pnijhara** [comment]
@salonigupta1 are you working on this issue?

**Comment by salonigupta1** [comment]
I will complete it by today.

**Comment by salonigupta1** [comment]
sorry for the delay

**Comment by syedjawadakhtar** [comment]
@salonigupta1 
You will have to add some guidelines for adding images/diagrams/figures:
1. All the images/figures/diagrams must always be added to a subfolder ```static```. Make the folder if it isn't present
2. ScreenShots should be considered over camera photos.
3. The format of naming the images must be: <document_name>_<serial number>. eg. ```online_CF_1.png``` for image in Online Crowd Funding.
4. Images must be properly **cropped**, must not be showing **OS or phone model/brand** in the images.
5. Every image must have caption about describing shortly about the figure. (_Adding the source of the image would be better_)

@pnijhara Add/Correct any points required.

**Comment by pnijhara** [comment]
What do you think! Should we make sub-directories in the static directory?
Sub-directories can be named as the name of the file they are referencing.

For example: If we have a file `pnijhara.md` in computers team and I am adding some images in this file. We can name the images as `pnijhara_n_content.png` in the directory `static/pnijhara` where n belongs the number/order of that image and content refers to the usage of that image.

**Comment by syedjawadakhtar** [comment]
I meant making a new directory of static folder in new folders,  like in the students_Reports folder. So that referencing images is easy. 
No subdirectories in existing static folder.

**Comment by pnijhara** [comment]
We should make sub-directories!

**Comment by syedjawadakhtar** [comment]
Okay
@salonigupta1 if you have any doubt do let us know!

**Comment by pnijhara** [comment]
@salonigupta1 first focus on the points that @syedjawadakhtar suggested.
