### ISSUE TITLE
Update mkdocs.yml

### ISSUE THREAD

**Issue by TamkeenFatima** [auvzhcet/Documentation#68]
**Is your feature request related to a problem? Please describe.**
1. Often, while switching from a document of one team to another, say a report from management to one of mechanical, the menu becomes too long and you have to scroll down all over to look for what you need.
2. I don't have a twitter account. If I wish to contact the organization, I will have to google about it. This may be inconvenient.

**Describe the solution you'd like**
1. We can have a main menu containing tabs for all parent directories with contextual links in the nav-bar.
2. All social links should be present in the footer. Link to official site of the club should also be present.

**Describe alternatives you've considered**
1. Add tabs feature.
2. Add social links. The twitter link in the footer (left end) can be replaced by the official site link.

**Additional context**

| ![tabs_feature](https://user-images.githubusercontent.com/60381216/87454570-c9cb8480-c621-11ea-8899-b0d6df43df80.PNG) |
| :---: |
| fig 1: Tabs feature |

| ![social_links](https://user-images.githubusercontent.com/60381216/87447192-e82c8280-c617-11ea-9ad7-3d7540a092a7.PNG) |
| :---: |
| fig 2: Social links of the organization (bottom right) |

**Some additional extensions that can be used to enhance the looks of the page:**

- 'Admonition extension'

| ![admonition_extension_example](https://user-images.githubusercontent.com/60381216/87446802-6a687700-c617-11ea-9239-c42cda61622d.PNG) |
| :---: |
| fig 3: An example (the note) of [admonition](https://squidfunk.github.io/mkdocs-material/extensions/admonition/) extension used in `index.md` |

- 'Codehiliting extension'

| ![codehilite_with_linenums](https://user-images.githubusercontent.com/60381216/87454701-f4b5d880-c621-11ea-9577-3ab3fec2a9d5.PNG) |
| :---: |
| fig 4: [Codehiliting](https://squidfunk.github.io/mkdocs-material/extensions/codehilite/) extension (with line numbers) |

\* The primary color may be changed to cyan for visual comfort. Also , we can have a different accent color (I used teal).
\* The font style may be changed to Times New Roman as it is a bit more professional.

**Comment by syedjawadakhtar** [comment]
LGTM! Please assign this issue to yourself and PR.
What say @pnijhara?

**Comment by pnijhara** [comment]
Nice write-up. Thank you for explaining the feature.

Coming to the feature request. I agree with the point that we need to add a footer with more social media links, go on with that.
I like that tabs feature too.
Tabs and admonitions also look good. But we need to look at the colour scheme of the docs, which we can discuss later in this issue. But for now please break this issue into sub-issues and take them one by one on yourself.

**Comment by TamkeenFatima** [comment]
> LGTM! Please assign this issue to yourself and PR.

I don't have the access, please do that for me.

**Comment by TamkeenFatima** [comment]
> Nice write-up. Thank you for explaining the feature.
> 
> Coming to the feature request. I agree with the point that we need to add a footer with more social media links, go on with that.
> I like that tabs feature too.
> Tabs and admonitions also look good. But we need to look at the colour scheme of the docs, which we can discuss later in this issue. But for now please break this issue into sub-issues and take them one by one on yourself.

OK.
I will start by adding the tabs feature.

**Comment by pnijhara** [comment]
Just open issues and write on them that you are working on them.

**Comment by TamkeenFatima** [comment]
OK

**Comment by pnijhara** [comment]
So for the colour scheme, I was thinking of going with the logo.

Black white and grey.
What say @syedjawadakhtar and @TamkeenFatima?

**Comment by syedjawadakhtar** [comment]
Would seem nice. @TamkeenFatima a preview would be better.

**Comment by TamkeenFatima** [comment]
Yeah, it would be great! Indeed, that was my first choice.

**Comment by TamkeenFatima** [comment]
| ![primary-black](https://user-images.githubusercontent.com/60381216/87701440-a0436200-c7b5-11ea-88b8-f982607bca3c.PNG) |
| :---: |
| Black as primary color |

A good point is that it has uniformity in header and footer!

**Comment by pnijhara** [comment]
Yes!
This looks awsome! Go for it.

**Comment by TamkeenFatima** [comment]
What about the accent color? Should we keep it red (my suggestion)  @syedjawadakhtar and @pnijhara?

**Comment by TamkeenFatima** [comment]
And suggest a font style also.

**Comment by pnijhara** [comment]
Go for red for now. No need to change font. Current one is working fine, IMHO!
