### ISSUE TITLE
Update Computer's students.md

### ISSUE THREAD

**Issue by yash1412** [auvzhcet/Documentation#70]
## Team Documentation
Add links of the report in the Student.md

**Comment by yash1412** [comment]
I am working on this.

**Comment by syedjawadakhtar** [comment]
Do you mean `students.md`? 
Also you don't have to comment that you are working on this... 
You have to FIRST state exactly what you will be doing in this issue THEN 'assign yourself' AND add a label in th right hand column.

**Comment by yash1412** [comment]
yes, By mistake i have written readme.md.
ok
